spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

## Firebase Settings
#firebase:
#  sdk:
#    path: ${FIREBASE_SDK_PATH}
#
## AWS S3 Settings
#cloud:
#  aws:
#    credentials:
#      access-key: ${S3_ACCESS_KEY}
#      secret-key: ${S3_SECRET_KEY}
#    s3:
#      bucket: ${S3_BUCKET_NAME}
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false

logging:
  level:
    sql: info